adminuser/urls.py
from django.urls import path
from adminuser.views import *
from django.contrib.auth import views as authentication_view
# from django.views import generic

app_name = 'adminuser'

urlpatterns = [
    
    path('',home, name="home"),
    path('viewuser/',viewuser, name="viewuser"),
    path('SignUp/',SignUp.as_view(), name="SignUp"),
    # path('login/', authentication_view.LoginView.as_view(template_name="login.html",authentication_form=CustomAuthForm), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/',authentication_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('noti/', Craetenotification.as_view(), name='noti'),
    path('notipageing/', NotificationList.as_view(), name='notipageing'),
]

userapi/urls.py
from django.urls import path
from .views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

appname = "user"

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    # path('PDFview/', UserPDFView.as_view(), name='PDFview'),
    path('PDFview1/', UserPDFView1.as_view(), name='PDFview1'),
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('showuser/', show_user, name='showuser'),
    path('create-pdf/', pdf_report_create, name='create-pdf'),
    # path('userpdf/', GeneratePDFView.as_view(), name='userpdf'),
    path('generate-pdf/', generate_pdf, name='generate_pdf'),
    path('user-pdf/', UserDataViewSet.as_view(), name='user-pdf'),
    
]

userapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('userapi.urls')),
    path('adminuser/', include('adminuser.urls')),
]

adminuser/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser,BaseUserManager
from django.contrib.auth.models import PermissionsMixin

# Create your models here.
class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email required')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be a staff'
            )
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be a superuser'
            )

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True,max_length=255,blank=False)
    first_name = models.CharField('first name',max_length=150,blank=True)
    last_name = models.CharField('last name',max_length=150,blank=True)
    mobile= models.PositiveBigIntegerField('mobile',null=True,blank=True)
    address=models.CharField('address',max_length=150,blank=True)
    is_staff = models.BooleanField('staff status',default=False)
    is_active = models.BooleanField('active',default=True)
    is_admin     = models.BooleanField(default=False)
    is_superuser = models.BooleanField('superuser',default=False)
    # date_joined = models.DateTimeField('date joined',default=timezone.now)
  
    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def full_name(self):
        return self.first_name+" "+self.last_name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

class Notification(models.Model):
    title = models.CharField(max_length=150,blank=True)
    body = models.CharField(max_length=150,blank=True)

adminuser/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth import get_user_model
from.models import *

class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email','mobile','address']
        labels = {'email': 'Email Address'}

class CustomAuthForm(AuthenticationForm):
        # email = forms.CharField(widget=TextInput(attrs={'class':'validate','placeholder': 'Email'}))
        # password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))
    def init(self, *args, **kwargs):
        super(CustomAuthForm, self).init(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

class NotificationForm(forms.Form):
    Title = forms.CharField(label='Title', widget=forms.TextInput)
    Body = forms.CharField(label='Body', widget=forms.TextInput)
    
    # class Meta:
    #     model = Notification
    #     fields = ['Title', 'Body']
    #     labels = {'Title': 'Title'}

adminuser/views.py
from .forms import *
from .models import *
from userapi.serializers import *
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.views import generic
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
from .forms import CustomAuthForm

# Create your views here.
def home(request):
    return render(request,'index.html')

class SignUp(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('adminuser:login')
    template_name = 'sign_up.html'

# def login_view(request):
#     if request.method == 'POST':
#         form = CustomAuthForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']
#             user = authenticate(request, username=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('success')
#             else:
#                 form.add_error(None, "Invalid login credentials")
#     else:
#         form = CustomAuthForm()
#     return render(request, 'login.html', {'form': form})

class CustomLoginView(LoginView):
    form_class = CustomAuthForm
    template_name = 'login.html'
    success_url = reverse_lazy('home')

@login_required
def viewuser(request):
    user = request.user
    print(user)
    # all user data
    # userdata = User.objects.all()
    # print(userdata)
    userdata1 = User.objects.get(email=user)
    print(userdata1)
    # print(userdata.Address)
    # print(userdata.Contactno)
    # print(userdata.email)

    # context={'u':userdata} 
    context={'u':userdata1} 
    return render(request,"viewuser.html", context)

from django.db.models.signals import post_save
from django.dispatch import receiver
import firebase_admin
from firebase_admin import credentials, messaging
import os
from django.conf import settings

service_account_key_path = settings.SERVICE_ACCOUNT_KEY_PATH
cred = credentials.Certificate(service_account_key_path)
firebase_admin.initialize_app(cred)

@receiver(post_save, sender=User)
def user_saved(sender, instance, **kwargs):

# Define the notification payload:
  notification = messaging.Notification(title='New User added!', body='Welcome to New User!')

# Define the message:
  message = messaging.Message(notification=notification, topic='user')

# Send the message:
  response = messaging.send(message)

# Print the response to check for any errors:
  print(response)

class Craetenotification(generic.CreateView):
    form_class = NotificationForm
    template_name = 'notification.html'


def create_notification(request):
    form = NotificationForm(request.POST)
    if form.is_valid():
        notification = form.save()
        notification.send_notification()
        return redirect('success')
    else:
        return render(request, 'create_notification.html', {'form': form})

from django.dispatch import receiver
@receiver(post_save, sender=Notification)
def send_notification(sender, instance,**kwargs):
    
        title = instance.title
        body = instance.body

        notification = messaging.Notification(title=title, body=body)

        # Define the message:
        message = messaging.Message(notification=notification, topic='notification')

        # Send the message:
        response = messaging.send(message)

        # Print the response to check for any errors:
        print(response)

from rest_framework.pagination import PageNumberPagination
from rest_framework.views import APIView
from rest_framework import generics

class MyPagination(PageNumberPagination):
    page_size = 20
    page_size_query_param = 'page_size'
    max_page_size = 100

from .mypagination import Mycustompagination

class NotificationList(generics.ListAPIView):
        queryset = Notification.objects.all()
        serializer_class = Notificationserializer
        pagination_class = Mycustompagination
        
# http://127.0.0.1:8000/adminuser/notipageing

adminuser/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Welcome to User site</h1>
        {% if user.is_authenticated %}

        <a href="{% url 'adminuser:noti' %}" class="px-2 py-4 text-gray-500
            text-lg font-semibold"> Add User Notification </a>
        <a href="{% url 'adminuser:logout' %}" class="px-2 py-4 text-gray-500
            text-lg font-semibold"> Logout </a>
        {% else %}
        <a href="{% url 'adminuser:login' %}" class="px-2 py-4 text-gray-500
            text-lg font-semibold"> Login </a>/
        <a href="{% url 'adminuser:SignUp' %}" class="px-2 py-4 text-gray-500
            text-lg font-semibold"> Sign up </a>
        {% endif %}

        
    </body>
</html>

adminuser/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1 class="text-2xl font-bold m-10 ">Login User</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 px-8 mb-4" method="post">
        {% csrf_token %}
        <!-- {{form}} -->

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username: </label>
            <div class="shadow apperence-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.username}}
            </div>
        </div>
        
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Password: </label>
            <div class="shadow apperence-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password}}
            </div>
        </div>
        
        <div class="mb-2">        
            <input class="shadow apperence-none border rounded py-2 px-3 mr-10 bg-green-500" type="submit" name=":login" value="Login">
        </div> 
    </form>
    <div class="m-10">Do not have an account?
        <a class="text-indigo-500" href="{% url 'adminuser:SignUp' %}"> Register </a>
    </div>

</body>
</html>

adminuser/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 class="text-2xl font-bold m-10 ">Thank you Vist angin! </h1>
</body>
</html>

adminuser/templates/notification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{form.as_p}}
    <input type="submit" name="Sumbit">
</body>
</html>

adminuser/templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 class="text-2xl font-bold m-10 ">Register User</h1>
    <div class="container py-5 ml-10">
        <form action="" method="post" novalidate>
            {% csrf_token %} 
            {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
            {% endfor %}
            <input class="shadow apperence-none border rounded py-2 px-3 ml-10 bg-green-500" type="submit" value="Submit">
        </form>    
            
            <div class="m-2">Do have an account?
                <a class="text-indigo-500" href="{% url 'adminuser:login' %}"> Login </a>
            </div>
        
    </div>
            <!-- message  -->
            {% if messages %}
                {% for message in messages %}
                    <small {% if messages.tags %} class="{{message.tags}}" {% endif%}> {{message}} </small>
                {% endfor %}
            {% endif %}
    
    
</body>
</html>

adminuser/templates/viewuser.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <div class="mt-5">Username: {{u.username}}</div>
        <div class="mt-5">Email: {{u.email}} </div>
        <div class="mt-5">Firstname:{{u.first_name}} </div>
        <div class="mt-5">Lastname: {{u.last_name}} </div>
        <div class="mt-5">Contactno: {{u.mobile}} </div>
        <div class="mt-5">Address:  {{u.address}} </div>

    </body>
</html>